#ifndef SCREEN_NAMES_INCLUDED
#define SCREEN_NAMES_INCLUDED

#define NO_SCREEN -1
#define MAIN_MENU 0
#define COURSE_MENU 1
#define GAME 2
#define TWO_PLAYER_ROLE_SELECTION 3
#define CONTROL_INFO 4

#endif
